
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  userId: 'userId',
  email: 'email',
  passwordHash: 'passwordHash',
  isVerified: 'isVerified',
  isTwoFactorEnabled: 'isTwoFactorEnabled',
  firstName: 'firstName',
  middleName: 'middleName',
  lastName: 'lastName',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastLogin: 'lastLogin',
  role: 'role'
};

exports.Prisma.TokensScalarFieldEnum = {
  id: 'id',
  email: 'email',
  token: 'token',
  type: 'type',
  expiresIn: 'expiresIn'
};

exports.Prisma.OrganizationScalarFieldEnum = {
  organizationId: 'organizationId',
  name: 'name',
  createdBy: 'createdBy',
  createdAt: 'createdAt'
};

exports.Prisma.Organization_UsersScalarFieldEnum = {
  organizationId: 'organizationId',
  userId: 'userId',
  role: 'role'
};

exports.Prisma.WarehousesScalarFieldEnum = {
  warehouseId: 'warehouseId',
  organizationId: 'organizationId',
  name: 'name',
  address: 'address',
  city: 'city',
  state: 'state',
  zip: 'zip',
  country: 'country',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.ProductsScalarFieldEnum = {
  productId: 'productId',
  organizationId: 'organizationId',
  name: 'name',
  sku: 'sku',
  barcode: 'barcode',
  createdAt: 'createdAt'
};

exports.Prisma.Nomenclature_CategoryScalarFieldEnum = {
  categoryId: 'categoryId',
  name: 'name'
};

exports.Prisma.NomenklaturyScalarFieldEnum = {
  nomenclatureId: 'nomenclatureId',
  categoryId: 'categoryId',
  name: 'name'
};

exports.Prisma.Nomenklatury_ProductsScalarFieldEnum = {
  nomenclatureId: 'nomenclatureId',
  productId: 'productId'
};

exports.Prisma.DocumentsScalarFieldEnum = {
  documentId: 'documentId',
  organizationId: 'organizationId',
  warehouseId: 'warehouseId',
  documentStatus: 'documentStatus',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.Documents_ProductsScalarFieldEnum = {
  documentProductId: 'documentProductId',
  documentId: 'documentId',
  productId: 'productId',
  quantityExpected: 'quantityExpected',
  quantityChecked: 'quantityChecked',
  updatedAt: 'updatedAt'
};

exports.Prisma.DevicesScalarFieldEnum = {
  deviceId: 'deviceId',
  organizationId: 'organizationId',
  deviceType: 'deviceType',
  deviceName: 'deviceName',
  qrToken: 'qrToken',
  assignedTo: 'assignedTo',
  lastSynced: 'lastSynced',
  createdAt: 'createdAt'
};

exports.Prisma.Scan_eventsScalarFieldEnum = {
  scanEventId: 'scanEventId',
  documentId: 'documentId',
  productId: 'productId',
  userId: 'userId',
  deviceId: 'deviceId',
  quantityDelta: 'quantityDelta',
  scannedAt: 'scannedAt',
  synced: 'synced'
};

exports.Prisma.Sync_logsScalarFieldEnum = {
  syncLogId: 'syncLogId',
  deviceId: 'deviceId',
  direction: 'direction',
  success: 'success',
  syncTime: 'syncTime'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};
exports.UserRole = exports.$Enums.UserRole = {
  ADMIN: 'ADMIN',
  REGULAR: 'REGULAR'
};

exports.TokenType = exports.$Enums.TokenType = {
  VERIFICATION: 'VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TWO_FACTOR: 'TWO_FACTOR'
};

exports.OrganizationRole = exports.$Enums.OrganizationRole = {
  ADMIN: 'ADMIN',
  WAREHOUSE_WORKER: 'WAREHOUSE_WORKER'
};

exports.WarehouseStatus = exports.$Enums.WarehouseStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

exports.Prisma.ModelName = {
  User: 'User',
  Tokens: 'Tokens',
  Organization: 'Organization',
  Organization_Users: 'Organization_Users',
  Warehouses: 'Warehouses',
  Products: 'Products',
  Nomenclature_Category: 'Nomenclature_Category',
  Nomenklatury: 'Nomenklatury',
  Nomenklatury_Products: 'Nomenklatury_Products',
  Documents: 'Documents',
  Documents_Products: 'Documents_Products',
  Devices: 'Devices',
  Scan_events: 'Scan_events',
  Sync_logs: 'Sync_logs'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
